In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.cross_validation import cross_val_score, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, BaggingClassifier
%matplotlib inline

/Users/natalie/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
#Ritika EDA
def eda(dataframe):
    print "Missing Values \n \n", dataframe.isnull().sum(),"\n" #find missing values
    print "Duplicate Rows \n", dataframe.duplicated().sum(),"\n" #find duplicated values
    print "Dataframe Types \n \n", dataframe.dtypes,"\n" #datatypes of each column
    print "Dataframe Shape \n", dataframe.shape,"\n" #number of rows and columns
    print "Dataframe Describe \n \n", dataframe.describe(include='all'),"\n" #Describe all columns
    for feature in dataframe: # Prints unique values for each column 
        print feature
        print dataframe[feature].nunique()

In [49]:
train_df = pd.read_csv('./merged_train.csv')
test_df = pd.read_csv('./merged_test.csv')

pd.set_option('display.max_columns',28) # where n is the number to show
train_df

,Unnamed: 0,Date,Species,Latitude,Longitude,WnvPresent,month,CULEX ERRATICUS,CULEX PIPIENS,CULEX PIPIENS/RESTUANS,CULEX RESTUANS,CULEX SALINARIUS,CULEX TARSALIS,CULEX TERRITANS,Last7Average_Temp,Last7Average_Windspeed,Last7Total_Rainfall,Last14Average_Temp,Last14Average_Windspeed,Last14Total_Rainfall,Last7Average_Daylight,Last14Average_Daylight,Last7Average_Departure,Last14Average_Departure
0,0,2007-05-29,CULEX PIPIENS/RESTUANS,41.954690,-87.800991,0,5,0,0,1,0,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
1,1,2007-05-29,CULEX RESTUANS,41.954690,-87.800991,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
2,2,2007-05-29,CULEX RESTUANS,41.994991,-87.769279,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
3,3,2007-05-29,CULEX PIPIENS/RESTUANS,41.974089,-87.824812,0,5,0,0,1,0,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
4,4,2007-05-29,CULEX RESTUANS,41.974089,-87.824812,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
5,5,2007-05-29,CULEX RESTUANS,41.921600,-87.666455,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
6,6,2007-05-29,CULEX RESTUANS,41.891118,-87.654491,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
7,7,2007-05-29,CULEX PIPIENS/RESTUANS,41.867108,-87.654224,0,5,0,0,1,0,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
8,8,2007-05-29,CULEX RESTUANS,41.867108,-87.654224,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
9,9,2007-05-29,CULEX RESTUANS,41.896282,-87.655232,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
10,10,2007-05-29,CULEX PIPIENS/RESTUANS,41.919343,-87.694259,0,5,0,0,1,0,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
11,11,2007-05-29,CULEX PIPIENS/RESTUANS,41.921965,-87.632085,0,5,0,0,1,0,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
12,12,2007-05-29,CULEX RESTUANS,41.921965,-87.632085,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
13,13,2007-05-29,CULEX PIPIENS/RESTUANS,41.688324,-87.676709,0,5,0,0,1,0,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
14,14,2007-05-29,CULEX RESTUANS,41.688324,-87.676709,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
15,15,2007-05-29,CULEX RESTUANS,41.862292,-87.648860,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
16,16,2007-05-29,CULEX RESTUANS,41.720848,-87.666014,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
17,17,2007-05-29,CULEX RESTUANS,41.731922,-87.677512,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
18,18,2007-05-29,CULEX PIPIENS,41.731922,-87.677512,0,5,0,1,0,0,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
19,19,2007-05-29,CULEX PIPIENS/RESTUANS,41.891126,-87.611560,0,5,0,0,1,0,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
20,20,2007-05-29,CULEX RESTUANS,41.891126,-87.611560,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
21,21,2007-05-29,CULEX PIPIENS/RESTUANS,41.999129,-87.795585,0,5,0,0,1,0,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
22,22,2007-05-29,CULEX PIPIENS/RESTUANS,42.017430,-87.687769,0,5,0,0,1,0,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
23,23,2007-05-29,CULEX RESTUANS,41.907645,-87.760886,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
24,24,2007-05-29,CULEX RESTUANS,41.732984,-87.649642,0,5,0,0,0,1,0,0,0,67.571429,10.014286,1.07,63.785714,10.264286,1.66,890.714286,884.357143,5.714286,3.000000
25,25,2007-06-05,CULEX PIPIENS/RESTUANS,41.954690,-87.800991,0,6,0,0,1,0,0,0,0,72.142857,8.171429,0.64,69.857143,9.092857,1.71,900.285714,895.500000,8.142857,6.928571
26,26,2007-06-05,CULEX RESTUANS,41.954690,-87.800991,0,6,0,0,0,1,0,0,0,72.142857,8.171429,0.64,69.857143,9.092857,1.71,900.285714,895.500000,8.142857,6.928571
27,27,2007-06-05,CULEX PIPIENS,41.954690,-87.800991,0,6,0,1,0,0,0,0,0,72.142857,8.171429,0.64,69.857143,9.092857,1.71,900.285714,895.500000,8.142857,6.928571
28,28,2007-06-05,CULEX PIPIENS/RESTUANS,41.974089,-87.824812,0,6,0,0,1,0,0,0,0,72.142857,8.171429,0.64,69.857143,9.092857,1.71,900.285714,895.500000,8.142857,6.928571
29,29,2007-06-05,CULEX RESTUANS,41.974089,-87.824812,0,6,0,0,0,1,0,0,0,72.142857,8.171429,0.64,69.857143,9.092857,1.71,900.285714,895.500000,8.142857,6.928571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10476,10476,2013-09-26,CULEX PIPIENS/RESTUANS,41.750498,-87.605294,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10477,10477,2013-09-26,CULEX RESTUANS,41.750498,-87.605294,0,9,0,0,0,1,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10478,10478,2013-09-26,CULEX PIPIENS,41.750498,-87.605294,0,9,0,1,0,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10479,10479,2013-09-26,CULEX PIPIENS,41.984809,-87.728492,0,9,0,1,0,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10480,10480,2013-09-26,CULEX PIPIENS/RESTUANS,41.659112,-87.538693,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10481,10481,2013-09-26,CULEX RESTUANS,41.659112,-87.538693,0,9,0,0,0,1,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10482,10482,2013-09-26,CULEX PIPIENS,41.659112,-87.538693,0,9,0,1,0,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10483,10483,2013-09-26,CULEX RESTUANS,41.992478,-87.862995,0,9,0,0,0,1,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10484,10484,2013-09-26,CULEX PIPIENS/RESTUANS,41.974689,-87.890615,1,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10485,10485,2013-09-26,CULEX PIPIENS/RESTUANS,41.974689,-87.890615,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10486,10486,2013-09-26,CULEX PIPIENS,41.974689,-87.890615,0,9,0,1,0,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10487,10487,2013-09-26,CULEX PIPIENS,41.974689,-87.890615,0,9,0,1,0,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10488,10488,2013-09-26,CULEX PIPIENS,41.974689,-87.890615,0,9,0,1,0,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10489,10489,2013-09-26,CULEX PIPIENS,41.974689,-87.890615,0,9,0,1,0,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10490,10490,2013-09-26,CULEX PIPIENS/RESTUANS,41.925198,-87.746381,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10491,10491,2013-09-26,CULEX PIPIENS/RESTUANS,41.973845,-87.805059,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10492,10492,2013-09-26,CULEX PIPIENS,41.973845,-87.805059,0,9,0,1,0,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10493,10493,2013-09-26,CULEX PIPIENS/RESTUANS,41.743402,-87.731435,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10494,10494,2013-09-26,CULEX PIPIENS/RESTUANS,41.728495,-87.600963,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10495,10495,2013-09-26,CULEX PIPIENS,41.728495,-87.600963,0,9,0,1,0,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10496,10496,2013-09-26,CULEX PIPIENS/RESTUANS,41.947227,-87.671457,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10497,10497,2013-09-26,CULEX PIPIENS/RESTUANS,41.793818,-87.654234,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10498,10498,2013-09-26,CULEX PIPIENS/RESTUANS,41.904194,-87.756155,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10499,10499,2013-09-26,CULEX PIPIENS,41.904194,-87.756155,0,9,0,1,0,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10500,10500,2013-09-26,CULEX PIPIENS/RESTUANS,41.951866,-87.725057,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10501,10501,2013-09-26,CULEX PIPIENS/RESTUANS,41.763733,-87.742302,1,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10502,10502,2013-09-26,CULEX PIPIENS/RESTUANS,41.987280,-87.666066,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10503,10503,2013-09-26,CULEX PIPIENS/RESTUANS,41.912563,-87.668055,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10504,10504,2013-09-26,CULEX PIPIENS/RESTUANS,42.009876,-87.807277,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857
10505,10505,2013-09-26,CULEX PIPIENS/RESTUANS,41.776428,-87.627096,0,9,0,0,1,0,0,0,0,62.857143,8.414286,0.84,62.857143,8.464286,2.04,730.428571,740.928571,1.142857,-0.142857

In [5]:
eda(train_df)

Missing Values

Date                       0
Last7Average_Temp          0
Last7Average_Windspeed     0
Last7Total_Rainfall        0
Last14Average_Temp         0
Last14Average_Windspeed    0
Last14Total_Rainfall       0
Last7Average_Daylight      0
Last14Average_Daylight     0
Last7Average_Departure     0
Last14Average_Departure    0
Species                    0
Latitude                   0
Longitude                  0
WnvPresent                 0
month                      0
CULEX PIPIENS              0
CULEX PIPIENS/RESTUANS     0
CULEX RESTUANS             0
CULEX SALINARIUS           0
CULEX TARSALIS             0
CULEX TERRITANS            0
dtype: int64

Duplicate Rows
1896

Dataframe Types

Date                        object
Last7Average_Temp          float64
Last7Average_Windspeed     float64
Last7Total_Rainfall        float64
Last14Average_Temp         float64
Last14Average_Windspeed    float64
Last14Total_Rainfall       float64
Last7Average_Daylight      float64
Last14Average_Daylight     float64
Last7Average_Departure     float64
Last14Average_Departure    float64
Species                     object
Latitude                   float64
Longitude                  float64
WnvPresent                   int64
month                        int64
CULEX PIPIENS                int64
CULEX PIPIENS/RESTUANS       int64
CULEX RESTUANS               int64
CULEX SALINARIUS             int64
CULEX TARSALIS               int64
CULEX TERRITANS              int64
dtype: object

Dataframe Shape
(10506, 22)

Dataframe Describe

              Date  Last7Average_Temp  Last7Average_Windspeed  \
count        10506       10506.000000            10506.000000
unique          95                NaN                     NaN
top     2007-08-01                NaN                     NaN
freq           551                NaN                     NaN
mean           NaN          71.647807                7.565276
std            NaN           5.694683                1.133245
min            NaN          57.428571                5.485714
25%            NaN          68.142857                6.685714
50%            NaN          71.857143                7.428571
75%            NaN          76.142857                8.514286
max            NaN          83.285714               10.300000

        Last7Total_Rainfall  Last14Average_Temp  Last14Average_Windspeed  \
count          10506.000000        10506.000000             10506.000000
unique                  NaN                 NaN                      NaN
top                     NaN                 NaN                      NaN
freq                    NaN                 NaN                      NaN
mean               1.143566           71.710934                 7.637746
std                1.794232            4.816254                 0.987895
min                0.000000           58.500000                 5.257143
25%                0.190000           68.857143                 6.771429
50%                0.570000           72.285714                 7.564286
75%                1.130000           74.357143                 8.357143
max               10.000000           81.500000                10.264286

        Last14Total_Rainfall  Last7Average_Daylight  Last14Average_Daylight  \
count           10506.000000           10506.000000            10506.000000
unique                   NaN                    NaN                     NaN
top                      NaN                    NaN                     NaN
freq                     NaN                    NaN                     NaN
mean                2.130276             847.599848              853.223226
std                 2.226660              59.422866               56.119889
min                 0.000000             694.285714              704.071429
25%                 0.640000             808.714286              818.000000
50%                 1.540000             866.428571              873.428571
75%                 2.630000             899.571429              901.928571
max                11.130000             914.000000              913.357143

        Last7Average_Departure  Last14Average_Departure  \
count             10506.000000             10506.000000
unique                     NaN                      NaN
top                        NaN                      NaN
freq                       NaN                      NaN
mean                  1.577779                 1.511850
std                   4.298069                 3.260911
min                  -8.428571                -5.785714
25%                  -1.571429                -0.285714
50%                   2.000000                 1.857143
75%                   4.428571                 4.142857
max                  15.000000                10.642857

                       Species      Latitude     Longitude    WnvPresent  \
count                    10506  10506.000000  10506.000000  10506.000000
unique                       7           NaN           NaN           NaN
top     CULEX PIPIENS/RESTUANS           NaN           NaN           NaN
freq                      4752           NaN           NaN           NaN
mean                       NaN     41.841139    -87.699908      0.052446
std                        NaN      0.112742      0.096514      0.222936
min                        NaN     41.644612    -87.930995      0.000000
25%                        NaN     41.732984    -87.760070      0.000000
50%                        NaN     41.846283    -87.694991      0.000000
75%                        NaN     41.954690    -87.627796      0.000000
max                        NaN     42.017430    -87.531635      1.000000

               month  CULEX PIPIENS  CULEX PIPIENS/RESTUANS  CULEX RESTUANS  \
count   10506.000000   10506.000000            10506.000000    10506.000000
unique           NaN            NaN                     NaN             NaN
top              NaN            NaN                     NaN             NaN
freq             NaN            NaN                     NaN             NaN
mean        7.692557       0.256901                0.452313        0.260803
std         1.067675       0.436945                0.497744        0.439094
min         5.000000       0.000000                0.000000        0.000000
25%         7.000000       0.000000                0.000000        0.000000
50%         8.000000       0.000000                0.000000        0.000000
75%         8.000000       1.000000                1.000000        1.000000
max        10.000000       1.000000                1.000000        1.000000

        CULEX SALINARIUS  CULEX TARSALIS  CULEX TERRITANS
count       10506.000000    10506.000000     10506.000000
unique               NaN             NaN              NaN
top                  NaN             NaN              NaN
freq                 NaN             NaN              NaN
mean            0.008186        0.000571         0.021131
std             0.090109        0.023892         0.143827
min             0.000000        0.000000         0.000000
25%             0.000000        0.000000         0.000000
50%             0.000000        0.000000         0.000000
75%             0.000000        0.000000         0.000000
max             1.000000        1.000000         1.000000

Date
95
Last7Average_Temp
64
Last7Average_Windspeed
75
Last7Total_Rainfall
69
Last14Average_Temp
75
Last14Average_Windspeed
84
Last14Total_Rainfall
76
Last7Average_Daylight
74
Last14Average_Daylight
75
Last7Average_Departure
68
Last14Average_Departure
73
Species
7
Latitude
138
Longitude
138
WnvPresent
2
month
6
CULEX PIPIENS
2
CULEX PIPIENS/RESTUANS
2
CULEX RESTUANS
2
CULEX SALINARIUS
2
CULEX TARSALIS
2
CULEX TERRITANS
2

In [9]:
# spray = pd.read_csv('./spray_train.csv')
# spray.head()
# from first model prep

In [6]:
eda(test_df)

Missing Values

Date                       0
Last7Average_Temp          0
Last7Average_Windspeed     0
Last7Total_Rainfall        0
Last14Average_Temp         0
Last14Average_Windspeed    0
Last14Total_Rainfall       0
Last7Average_Daylight      0
Last14Average_Daylight     0
Last7Average_Departure     0
Last14Average_Departure    0
Id                         0
Species                    0
Latitude                   0
Longitude                  0
month                      0
CULEX PIPIENS              0
CULEX PIPIENS/RESTUANS     0
CULEX RESTUANS             0
CULEX SALINARIUS           0
CULEX TARSALIS             0
CULEX TERRITANS            0
UNSPECIFIED CULEX          0
dtype: int64

Duplicate Rows
0

Dataframe Types

Date                        object
Last7Average_Temp          float64
Last7Average_Windspeed     float64
Last7Total_Rainfall        float64
Last14Average_Temp         float64
Last14Average_Windspeed    float64
Last14Total_Rainfall       float64
Last7Average_Daylight      float64
Last14Average_Daylight     float64
Last7Average_Departure     float64
Last14Average_Departure    float64
Id                           int64
Species                     object
Latitude                   float64
Longitude                  float64
month                        int64
CULEX PIPIENS                int64
CULEX PIPIENS/RESTUANS       int64
CULEX RESTUANS               int64
CULEX SALINARIUS             int64
CULEX TARSALIS               int64
CULEX TERRITANS              int64
UNSPECIFIED CULEX            int64
dtype: object

Dataframe Shape
(116293, 23)

Dataframe Describe

              Date  Last7Average_Temp  Last7Average_Windspeed  \
count       116293      116293.000000           116293.000000
unique          95                NaN                     NaN
top     2012-07-09                NaN                     NaN
freq          1293                NaN                     NaN
mean           NaN          72.704729                8.113734
std            NaN           5.735498                1.428637
min            NaN          54.142857                5.428571
25%            NaN          68.714286                7.042857
50%            NaN          73.000000                7.928571
75%            NaN          76.857143                9.042857
max            NaN          87.142857               12.171429

        Last7Total_Rainfall  Last14Average_Temp  Last14Average_Windspeed  \
count         116293.000000       116293.000000            116293.000000
unique                  NaN                 NaN                      NaN
top                     NaN                 NaN                      NaN
freq                    NaN                 NaN                      NaN
mean               1.199887           72.822536                 8.200404
std                1.758059            4.948461                 1.106532
min                0.000000           58.785714                 5.842857
25%                0.170000           69.214286                 7.328571
50%                0.560000           73.071429                 8.092857
75%                1.440000           76.357143                 8.757143
max                9.680000           82.785714                11.328571

        Last14Total_Rainfall  Last7Average_Daylight  Last14Average_Daylight  \
count          116293.000000          116293.000000           116293.000000
unique                   NaN                    NaN                     NaN
top                      NaN                    NaN                     NaN
freq                     NaN                    NaN                     NaN
mean                2.179253             849.224689              854.591298
std                 2.168623              60.236823               56.675099
min                 0.010000             713.857143              723.500000
25%                 0.740000             803.428571              812.785714
50%                 1.520000             866.428571              873.428571
75%                 3.120000             904.285714              904.142857
max                12.610000             914.000000              913.357143

        Last7Average_Departure  Last14Average_Departure             Id  \
count            116293.000000            116293.000000  116293.000000
unique                     NaN                      NaN            NaN
top                        NaN                      NaN            NaN
freq                       NaN                      NaN            NaN
mean                  2.746031                 2.773507   58147.000000
std                   4.032462                 3.247153   33571.041765
min                 -10.285714                -4.500000       1.000000
25%                  -0.285714                 0.785714   29074.000000
50%                   3.000000                 3.000000   58147.000000
75%                   5.714286                 4.857143   87220.000000
max                  15.000000                10.500000  116293.000000

                       Species       Latitude      Longitude          month  \
count                   116293  116293.000000  116293.000000  116293.000000
unique                       8            NaN            NaN            NaN
top     CULEX PIPIENS/RESTUANS            NaN            NaN            NaN
freq                     15359            NaN            NaN            NaN
mean                       NaN      41.849389     -87.693658       7.620244
std                        NaN       0.106593       0.080699       1.065842
min                        NaN      41.644612     -87.930995       6.000000
25%                        NaN      41.753411     -87.750938       7.000000
50%                        NaN      41.862292     -87.694991       8.000000
75%                        NaN      41.951866     -87.648860       8.000000
max                        NaN      42.017430     -87.531635      10.000000

        CULEX PIPIENS  CULEX PIPIENS/RESTUANS  CULEX RESTUANS  \
count   116293.000000           116293.000000   116293.000000
unique            NaN                     NaN             NaN
top               NaN                     NaN             NaN
freq              NaN                     NaN             NaN
mean         0.124866                0.132072        0.126147
std          0.330568                0.338570        0.332016
min          0.000000                0.000000        0.000000
25%          0.000000                0.000000        0.000000
50%          0.000000                0.000000        0.000000
75%          0.000000                0.000000        0.000000
max          1.000000                1.000000        1.000000

        CULEX SALINARIUS  CULEX TARSALIS  CULEX TERRITANS  UNSPECIFIED CULEX
count      116293.000000   116293.000000    116293.000000      116293.000000
unique               NaN             NaN              NaN                NaN
top                  NaN             NaN              NaN                NaN
freq                 NaN             NaN              NaN                NaN
mean            0.123438        0.123369         0.123404           0.123352
std             0.328941        0.328862         0.328902           0.328842
min             0.000000        0.000000         0.000000           0.000000
25%             0.000000        0.000000         0.000000           0.000000
50%             0.000000        0.000000         0.000000           0.000000
75%             0.000000        0.000000         0.000000           0.000000
max             1.000000        1.000000         1.000000           1.000000

Date
95
Last7Average_Temp
68
Last7Average_Windspeed
82
Last7Total_Rainfall
65
Last14Average_Temp
72
Last14Average_Windspeed
90
Last14Total_Rainfall
83
Last7Average_Daylight
79
Last14Average_Daylight
80
Last7Average_Departure
58
Last14Average_Departure
68
Id
116293
Species
8
Latitude
151
Longitude
151
month
5
CULEX PIPIENS
2
CULEX PIPIENS/RESTUANS
2
CULEX RESTUANS
2
CULEX SALINARIUS
2
CULEX TARSALIS
2
CULEX TERRITANS
2
UNSPECIFIED CULEX
2

In [8]:
# trainduplicates = pd.read_csv("./df_train.csv")
# pd.set_option('display.max_columns',45) # where n is the number to show
# train
# from first model prep

In [100]:
# train = trainduplicates.drop_duplicates()
# we decided to keep dups as they deal with traps containing more than 50 per observation

In [123]:
# merged = train.merge(weather, left_on='Date', right_on ='Date', how= 'inner')
# from our first model prep

In [7]:
# pd.set_option('max_columns', None)
# merged.head()
# from our first model prep

In [10]:
# merged['Geo'] = merged['Latitude'].map(str) + ', ' + merged["Longitude"].map(str)
# merged.head()
# merged['Geo'].nunique() 
# from our first prep

In [11]:
# merged['Trap'].nunique()

In [119]:
# merged['Lat2'] = merged['Latitude'].astype('float64')

In [12]:
# merged['Lat2'].value_counts()

In [120]:
# merged['Long2'] = merged['Longitude'].astype('float64')

In [13]:
# merged['Long2'].value_counts()

In [14]:
# trap_dummies = pd.get_dummies(merged['Trap']).iloc[:, 1:]
# trap_dummies
# from first prep

In [15]:
#trap_dummies = trap_dummies.loc[:, 'T002':].astype('int64')

In [16]:
#trap_dummies.dtypes

In [165]:
#species_dummies = species_dummies.loc[:, 'CULEX PIPIENS':].astype('int64')

In [28]:
#species_dummies.columns

In [27]:
#species_dummies.dtypes

In [20]:
# species_dummies = pd.get_dummies(train_df['Species']).iloc[:, 1:]
# # dummies = pd.concat([trap_dummies, species_dummies], axis=1)
# # dummies from first model
# species_dummies

In [62]:
# mergedclean = merged
# mergedclean.replace('M',np.nan)
# mergedclean.dropna(axis=0, inplace=True)
# mergedclean.drop_duplicates(inplace=True)
# mergedclean
# eda(mergedclean)

In [26]:
# x = merged[['WnvPresent','NumMosquitos','Last7Average_Windspeed','Last7Average_Temp','Last7Total_Rainfall','month']]
# modeldf = pd.concat([x, dummies],axis=1)
# modeldf

In [50]:
test_df.columns

Index([u'Unnamed: 0', u'Id', u'Date', u'Species', u'Latitude', u'Longitude',
       u'month', u'CULEX ERRATICUS', u'CULEX PIPIENS',
       u'CULEX PIPIENS/RESTUANS', u'CULEX RESTUANS', u'CULEX SALINARIUS',
       u'CULEX TARSALIS', u'CULEX TERRITANS', u'UNSPECIFIED CULEX',
       u'Last7Average_Temp', u'Last7Average_Windspeed', u'Last7Total_Rainfall',
       u'Last14Average_Temp', u'Last14Average_Windspeed',
       u'Last14Total_Rainfall', u'Last7Average_Daylight',
       u'Last14Average_Daylight', u'Last7Average_Departure',
       u'Last14Average_Departure'],
      dtype='object')

In [51]:
test_df = test_df[['Id', 'Last7Average_Temp', 'Last7Average_Windspeed', 'Last7Total_Rainfall', 'Last14Average_Temp', 
                     'Last14Average_Windspeed', 'Last14Total_Rainfall', 'Last7Average_Daylight', 'Last14Average_Daylight', 
                     'Last7Average_Departure', 'Last14Average_Departure', 'Latitude', 'Longitude', 'month', 
                     'CULEX PIPIENS', 'CULEX PIPIENS/RESTUANS', 'CULEX ERRATICUS', 'CULEX RESTUANS', 'UNSPECIFIED CULEX', 'CULEX SALINARIUS', 'CULEX TARSALIS', 'CULEX TERRITANS']]

In [45]:
test_df.columns

Index([u'Id', u'Last7Average_Temp', u'Last7Average_Windspeed',
       u'Last7Total_Rainfall', u'Last14Average_Temp',
       u'Last14Average_Windspeed', u'Last14Total_Rainfall',
       u'Last7Average_Daylight', u'Last14Average_Daylight',
       u'Last7Average_Departure', u'Last14Average_Departure', u'Latitude',
       u'Longitude', u'month', u'CULEX PIPIENS', u'CULEX PIPIENS/RESTUANS',
       u'CULEX ERRATICUS', u'CULEX RESTUANS', u'UNSPECIFIED CULEX',
       u'CULEX SALINARIUS', u'CULEX TARSALIS', u'CULEX TERRITANS'],
      dtype='object')

In [46]:
train_df.columns

Index([u'Date', u'Last7Average_Temp', u'Last7Average_Windspeed',
       u'Last7Total_Rainfall', u'Last14Average_Temp',
       u'Last14Average_Windspeed', u'Last14Total_Rainfall',
       u'Last7Average_Daylight', u'Last14Average_Daylight',
       u'Last7Average_Departure', u'Last14Average_Departure', u'Species',
       u'Latitude', u'Longitude', u'WnvPresent', u'month', u'CULEX PIPIENS',
       u'CULEX PIPIENS/RESTUANS', u'CULEX RESTUANS', u'CULEX SALINARIUS',
       u'CULEX TARSALIS', u'CULEX TERRITANS'],
      dtype='object')

In [36]:
train_df = train_df[['WnvPresent', 'Last7Average_Temp', 'Last7Average_Windspeed', 'Last7Total_Rainfall', 'Last14Average_Temp', 
                     'Last14Average_Windspeed', 'Last14Total_Rainfall', 'Last7Average_Daylight', 'Last14Average_Daylight', 
                     'Last7Average_Departure', 'Last14Average_Departure', 'Latitude', 'Longitude', 'month', 
                     'CULEX PIPIENS', 'CULEX PIPIENS/RESTUANS', 'CULEX RESTUANS', 'CULEX SALINARIUS', 'CULEX TARSALIS', 'CULEX TERRITANS']]

In [37]:
train_df.columns

Index([u'WnvPresent', u'Last7Average_Temp', u'Last7Average_Windspeed',
       u'Last7Total_Rainfall', u'Last14Average_Temp',
       u'Last14Average_Windspeed', u'Last14Total_Rainfall',
       u'Last7Average_Daylight', u'Last14Average_Daylight',
       u'Last7Average_Departure', u'Last14Average_Departure', u'Latitude',
       u'Longitude', u'month', u'CULEX PIPIENS', u'CULEX PIPIENS/RESTUANS',
       u'CULEX RESTUANS', u'CULEX SALINARIUS', u'CULEX TARSALIS',
       u'CULEX TERRITANS'],
      dtype='object')

In [ ]:
# species_dummies = pd.get_dummies(train_df['Species']).iloc[:, 1:]
# # dummies = pd.concat([trap_dummies, species_dummies], axis=1)
# # dummies from first model
# species_dummies

In [52]:
# merged['Date'] = pd.to_datetime(merged.Date)

In [ ]:
# x = merged[['WnvPresent','NumMosquitos','Last7Average_Windspeed','Last7Average_Temp','Last7Total_Rainfall','month']]
# modeldf = pd.concat([x, dummies],axis=1)
# # modeldf
# from first model

In [38]:
train_df.to_csv('train_model_2.0.csv',index=False)

In [34]:
test_df.to_csv('test_model_2.0.csv',index=False)